### ISSUE TITLE
No fine-tuning BERT?

### ISSUE THREAD

**Issue by sihyun-yu** [koustuvsinha/clutrr-baselines#2]
Hi, it seems the current implementation of BERT is frozen (w/o fine-tuning), and I want to ask is it intended or not. Thank you for the nice work and for sharing baseline codes btw!

**Comment by koustuvsinha** [comment]
Hi @sihyun-yu ! Sorry for the delayed reply! Yes in this paper we didn't finetune the entire BERT pipeline, we only took the frozen representation and learned the classifier layer and an LSTM layer on top of the BERT representations. This was primarily done to circumvent the anonymous entity issue. 

In hindsight if I were to re-do that experiment today, I would finetune the entire BERT model by providing special placeholder tokens to the Tokenizer. Let me know if you have success using that technique!
